AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Lambda for interacting with AI

Resources:
  AiGeneratorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: aiGeneratorFunction
      Handler: dist/index.handler
      Runtime: nodejs22.x
      CodeUri: ./dist/
      MemorySize: 128
      Timeout: 60
      Environment:
        Variables:
          RATE_LIMIT_WINDOW_MS: "28800000"
          FREE_USER_LIMIT: "2"
          PREMIUM_USER_LIMIT: "25"
          USER_PROFILE_TABLE_NAME: "UserProfileTable"
          MIGRATION_STATUS_TABLE_NAME: "app_migration_status"
          MIGRATION_STATUS_TTL_DAYS: "180"
          REQUIRE_COGNITO_AUTH: "false"
          ALLOW_UNAUTH_PREMIUM_OVERRIDE: "false"
      Policies:
        - Version: "2012-10-17"
          Statement:
            # Updated Secrets Manager permission
            - Effect: Allow
              Action: 
                - secretsmanager:GetSecretValue
              Resource: 
                - !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:prod/repvault-backend-ai/gemini-key*"
            # Add DynamoDB permissions
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:UpdateItem
              Resource: !GetAtt UserUsageTable.Arn
            - Effect: Allow
              Action:
                - dynamodb:GetItem
              Resource: !GetAtt UserProfileTable.Arn
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:UpdateItem
                - dynamodb:Scan
              Resource: !GetAtt AppMigrationStatusTable.Arn

  MyHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: prod
      Auth:
        EnableIamAuthorizer: false
      CorsConfiguration:
        AllowMethods:
          - POST
          - OPTIONS
        AllowOrigins:
          - "*"
      DefinitionBody:
        openapi: 3.0.1
        info:
          title: MyGeminiLambdaAPI
          version: '1.0'
        paths:
          /generate:
            post:
              x-amazon-apigateway-integration:
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${AiGeneratorFunction.Arn}/invocations
                httpMethod: POST
                type: aws_proxy

  AiGeneratorFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref AiGeneratorFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${MyHttpApi}/*"

  UserUsageTable: # Add the DynamoDB Table resource
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: UserUsageTable
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST # Or ProvisionedThroughput if preferred

  UserProfileTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: UserProfileTable
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  AppMigrationStatusTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: app_migration_status
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      BillingMode: PAY_PER_REQUEST
