AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Lambda for generating AI workouts using Gemini 2.0 Flash API

Resources:
  AIGeneratorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: aiGeneratorFunction
      Handler: index.handler  # Changed from dist/index.handler
      Runtime: nodejs18.x
      CodeUri: ./src/  # Changed from ./dist/
      MemorySize: 256
      Timeout: 30
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: 
                - !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:GeminiApiKeySecret*"
      Environment:
        Variables:
          GEMINI_API_URL: "https://api.gemini.com/flash"
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoint: index.ts  # Changed from src/index.ts
        Bundle: true

  MyHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: prod
      CorsConfiguration:
        AllowMethods:
          - POST
          - OPTIONS
        AllowOrigins:
          - "*"
      DefinitionBody:
        openapi: 3.0.1
        info:
          title: AIGeneratorAPI
          version: '1.0'
        paths:
          /generate:
            post:
              x-amazon-apigateway-integration:
                uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${AIGeneratorFunction.Arn}/invocations
                httpMethod: POST
                type: aws_proxy
              responses: {}

  AIGeneratorFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref AIGeneratorFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${MyHttpApi}/*