name: Deploy SAM Application

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Upgrade build tools
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Install SAM CLI with workaround for PyYAML
        run: |
          pip3 install wheel \
          && pip3 install --no-build-isolation "Cython<3" "pyyaml==5.4.1" \
          && pip3 install --upgrade --no-cache-dir aws-sam-cli

      - name: Install Node.js dependencies
        run: yarn install

      - name: Build TypeScript Code
        run: yarn build

      - name: Build SAM Application
        run: sam build

      - name: Deploy SAM Application
        run: |
          sam deploy --template-file template.yml --no-confirm-changeset --stack-name repvaultBackendAi --capabilities CAPABILITY_IAM --region us-east-1 --s3-bucket repvaul-ai-file-storage-s3-bucket
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
